[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist" # Adjust this to match the output directory of your build script

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
