[build]
[build]
  base = "fan2"
  command = "npm run build"
  publish = "fan2/dist"
  functions = "fan2/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
# Add more headers as needed
